### ISSUE TITLE
Publicación inicial de la dependencia en npm

### ISSUE THREAD

**Issue by faparraf** [udistrital/oidc-auth-js#1]
La organización busca que sea publicada una primera versión de oidc-auth-js en npm con el fin de iniciar la integración con un cliente definido (PHP) para satisfacer las necesidades de centralización de los mecanismos de autenticación de una forma estandar y accesible.

**Criterios de aceptación**
- [x] Librería publicada en npm
-  [x] Documentación de la librería en forma adecuada cumpliendo el estándar mínimo establecido en npm
- [x] Código en la rama default

**Comment by OscarDuarte7** [comment]
Se realizó el commit https://github.com/udistrital/oidc-auth-js/commit/1811d9fef9baf992acd7bf3bc95d776afee8e5b8 en el cual se crearon los archivos para publicación en npm.

**Comment by OscarDuarte7** [comment]
Se publicó libreria en https://www.npmjs.com/package/oidc-auth
