### ISSUE TITLE
Implementación de flujo OIDC en SARA

### ISSUE THREAD

**Issue by faparraf** [udistrital/oidc-auth-js#10]
Es necesario implementar las clases PHP desarrolladas y la librería JS OIDC sobre una aplicación SARA (Argo) y **evaluar** las redirecciones y consumos de recursos de forma correcta con el fin de dar el paso hacia una autenticación centralizada en las aplicaciones legadas de la organización.

**Criterios de aceptación:**
- [x] Aplicación Argo desplegada en ambiente de pruebas con evidencias gráficas del despliegue
- [x] Convivencia del código actual junto con el código nuevo

**Comment by OscarDuarte7** [comment]
Se revisó la inyección de javascript en las clases de php de acuerdo con lo consultado en:
 - https://www.quora.com/How-do-you-write-JavaScript-code-inside-PHP
- https://php.net/manual/en/language.types.string.php#language.types.string.syntax.nowdoc 

Con el objetivo de realizar la correcta inyección de la implementación de la libreria javascript en la clase bootstrap, la cual realiza el inicio de la aplicación.  Se le solicitó al ingeniero Andrey la explicación en cuanto al flujo que se sigue en el código de la aplicación.

**Comment by OscarDuarte7** [comment]
Se usan las clases de sara para la creación de la sesión pero se generan errores, como si no se encontraran los archivos:

Warning: include_once(core/log/logger.class.php): failed to open stream: No such file or directory in /var/www/html/blocks/acceso/login/funcion/formProcessor.php on line 7

Warning: include_once(): Failed opening 'core/log/logger.class.php' for inclusion (include_path='.:/usr/local/lib/php') in /var/www/html/blocks/acceso/login/funcion/formProcessor.php on line 7

Fatal error: Using $this when not in object context in /var/www/html/blocks/acceso/login/funcion/formProcessor.php on line 160

Por lo cual se le solicitó al ingeniero Andrey coloaboración en el asunto.

**Comment by jdc996** [comment]
Se implementa la autenticacion mediante Wso2 en argo para el navegador de chrome, se setea el acces token en una cookie y se almacena en sara, junto con el id del usuario
