### ISSUE TITLE
Generación de documentación de implementación

### ISSUE THREAD

**Issue by faparraf** [udistrital/oidc-auth-js#11]
La organización requiere una documentación de la implementación del flujo OIDC en las aplicaciones PHP-SARA con el fin de replicar dichos flujos en otras aplicaciones que posee la organización bajo la misma tecnología. Dicha documentación debe incluir los **detalles técnicos** necesarios para que el flujo sea funcional y correcto, así como las aclaraciones de cómo no interrumpir los manejos de sesiones actuales.

**Criterios de aceptación:**
- [x] Documentación publicada en GDrive de la organización.

**Comment by jdc996** [comment]
Se agrega la documentacion para la implementacion de autenticacion unica en argo
https://docs.google.com/document/d/1scF8lmOVYFtqT38nBqut1mn-jQQAPnTmGacEz6qwnzI/edit
