### ISSUE TITLE
Implementación sobre cliente Angular

### ISSUE THREAD

**Issue by faparraf** [udistrital/oidc-auth-js#12]
La organización requiere que el flujo OIDC que se definió bajo la librería JavaScript sea **implementado en una aplicación Angular** específica (_configuración_cliente_) con el fin de estandarizar el uso de la librería así como del flujo OIDC.

**Criterios de aceptación:**
- [x] Cliente desplegado con la librería implementada.
- [x] Pruebas iniciales sobre el cliente (login, logout, refresh)
> Referenciar este Issue desde el repositorio del cliente con `udistrital/oidc-auth-js#12`

**Comment by OscarDuarte7** [comment]
Se implementa autenticación usando la libreria en el cliente de configuración (Angular 7), en el commit:
https://github.com/udistrital/configuracion_v2_cliente/commit/6777d5ee4a5726218db7068d16447fb404e46555

**Comment by OscarDuarte7** [comment]
Se desplegó la implementación de la libreria en el 254. http://10.20.0.254/configuracionv2

**Comment by OscarJVD** [comment]
El enlace está roto, no funciona
