### ISSUE TITLE
Generar documentación de implementación Angular

### ISSUE THREAD

**Issue by faparraf** [udistrital/oidc-auth-js#13]
Se es requerido por la organización que la implementación de la librería OIDS JS en _Angular_ sea documentada con el fin de poder replicar de forma sencilla dicho proceso de estandarización. Dicha documentación debe incluir los detalles técnicos necesarios para la replicación del proceso así como la generalidad suficiente para diferentes escenarios.

**Criterios de aceptación:**
- [x] Documentación publicada en el Drive de la organización.

**Comment by OscarDuarte7** [comment]
Se realiza documentación en : https://docs.google.com/document/d/141e1dBQ3q0PjOdSujk6c7xebKz0ypjkrAyRqNC-e95o/edit

**Comment by OscarJVD** [comment]
No sirve el logout
