### ISSUE TITLE
Flujo OIDC en su primera versión en npm

### ISSUE THREAD

**Issue by faparraf** [udistrital/oidc-auth-js#2]
La organización requiere que se establezca una **primera versión** de un flujo OIDC sobre la dependencia npm con el fin de iniciar las pruebas de autenticación sobre los diferentes clientes que implementarán dicha dependencia sobre sus flujos de autenticación, y de esta manera obtener de primera mano una retroalimentación para la finalización de dicho flujo sobre este desarrollo (flujo personalizado).

**Entregables:**
- [x] Primera versión de un flujo OIDC publicado
- [x] Dependencia pública y accesible desde clientes

**Criterios de aceptación:**
- Código en la rama _default_

**Comment by OscarDuarte7** [comment]
Se revisó la forma en la que se deben consumir las librerias o modulos creados en ECMA script 6 desde javascript para poder ser utilizadas desde PHP.

Referencia:

https://developers.google.com/web/fundamentals/primers/modules

**Comment by OscarDuarte7** [comment]
Se publicó primera versión funcional del módulo en https://www.npmjs.com/package/oidc-auth
