### ISSUE TITLE
Flujo OIDC implementado y funcional

### ISSUE THREAD

**Issue by faparraf** [udistrital/oidc-auth-js#3]
Es requerido por la organización que la librería cuente con un flujo OIDC implementado en su totalidad con las parametrizaciones necesarias con el fin de iniciar la implementación de los flujos de autenticación y sesión. Es importante que la documentación que referencie el paquete de npm esté clara y especifique cómo implementarla y configurarla (parametrizaciones).

**Criterios de Aceptación:**
- [ ] Documentación completa y clara
- [x] Flujo OIDC completo

**Comment by OscarDuarte7** [comment]
En el commit https://github.com/udistrital/oidc-auth-js/commit/d00c9b82c2895b8ab8454da6fb6f2a6d410fe02d se actualiza el readme en la rama dev
